### ISSUE TITLE
Bad format when getting lairs

### ISSUE THREAD

**Issue by irevoire** [NoodleSamaChan/airbnb#2]
Hey,

When getting lairs from your API I was expecting the API to return an array of objects like that:
```
[
  {
    "id": 1,
    "title": "Le vigan",
    "description": "Blablabla",
    "lat": 42,
    "lng": 35
  },
  { "..." }
]
```

But instead, I get an array of array like that:
```
[
  [1, "Le vigan", "Blablabla", 42, 35],
  ["..."]
]
```

**Comment by NoodleSamaChan** [comment]
fixed by b0de1906840e7ec51dd2ffcd3774ec7d61bc694b
Thanks :)
