### ISSUE TITLE
Lairs are badly registered

### ISSUE THREAD

**Issue by irevoire** [NoodleSamaChan/airbnb#3]
Hey,

I found a strange bug in this project.
When sending a request to the API and then getting the lair back the latitude and longitude are modified with wrong value:
```bash
% echo '{ "title": "a", "description": "b", "image": "http", "lat": 0.60, "lon": 0.80 }' | http POST 'http://127.0.0.1:5000/lair' "Content-Type:application/json"
{
    "status": "success"
}
http GET '127.0.0.1:5000/lair/1'
[
    1,
    "a",
    "http",
    "b",
    1,
    1
]
```

Here as you can see, I sent the `0.60` for the latitude and `0.80` for the longitude both get rounded up to 1, that's not expected.

**Comment by NoodleSamaChan** [comment]
fixed by 3ecce87a483ec355a8b94be3886c569eede52238
thanks :)
